// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqbzdwvfgbkczwbjdbfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxYnpkd3ZmZ2JrY3p3YmpkYmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MzY4MjIsImV4cCI6MjA2MDUxMjgyMn0.b6qJZaVRAahkvw9LKAX0UiC3fMNSmdBxqOCruR7MH68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);